/* confdefs.h */
#define PACKAGE_NAME "libogg"
#define PACKAGE_TARNAME "libogg"
#define PACKAGE_VERSION "1.3.1"
#define PACKAGE_STRING "libogg 1.3.1"
#define PACKAGE_BUGREPORT "ogg-dev@xiph.org"
#define PACKAGE_URL ""
#define PACKAGE "libogg"
#define VERSION "1.3.1"
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_DLFCN_H 1
#define LT_OBJDIR ".libs/"
#define STDC_HEADERS 1
#define SIZEOF_INT16_T 2
#define SIZEOF_UINT16_T 2
#define SIZEOF_U_INT16_T 2
#define SIZEOF_INT32_T 4
#define SIZEOF_UINT32_T 4
#define SIZEOF_U_INT32_T 4
#define SIZEOF_INT64_T 8
#define SIZEOF_SHORT 2
#define SIZEOF_INT 4
#define SIZEOF_LONG 8
#define SIZEOF_LONG_LONG 8
